---
version: "3.9"

services:
  # jenkins:
  #   image: jenkinsci/blueocean
  #   environment:
  #     #### WINDOWS ONLY ####
  #     - DOCKER_HOST=tcp://host.docker.internal:2375
  #     ##### Mac OS X and Linux ONLY #####
  #     # - /var/run/docker.sock:/var/run/docker.sock
  #   user: root
  #   ports:
  #     - "8082:8082"
  #     - "8443:8443"
  #     - "50000:50000"
  #   volumes:
  #     - ./jenkins_data:/var/jenkins_home
  mongodb:
    # hostname: mongo1
    # container_name: localmongo1
    image: mongo
    logging:
      driver: none
    # expose:
    #   - 27017
    ports:
      - 27017:27017
    restart: always
    # networks:
    #   default:
    # entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
    # volumes:
    #   - mongodb:/var/lib/mongodb/data

  app:
    build: .
    # command: bundle exec ruby routes/books.rb
    volumes:
      - .:/src
    expose:
      - 8081/tcp
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      - APP_ENV=development
      - MONGO_ATLAS=true
      - MONGO_HOST=dummyCluster
      - MONGO_PORT=27017
      - MONGO_DB=dummyDB
      - MONGO_USER=dummyuser
      - MONGO_PASSWORD=dummypass
      - MONGO_SSL=false
    # entrypoint: ["ruby", "/app/routes/books.rb", "-s", "puma"]

    # redis:
    # image: "redis:alpine"
