apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-ruby-api
  namespace: myapps-ns
  labels:
    app: myapp-ruby-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-ruby-api
  template:
    metadata:
      labels:
        app: myapp-ruby-api
    spec:
      containers:
        - name: myapp-ruby-api
          image: docker.io/kponnima86/myapp-ruby-api:latest
          # command: [ "/bin/sh", "-c", "ls /etc/config/" ]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "100Mi"
              cpu: "300m"
            limits:
              memory: "200Mi"
              cpu: "600m"
          # volumeMounts:
          #   - name: config-volume
          #     mountPath: /etc/config
          # env:
          #   - name: PORT
          #     value: "8082"
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8081
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   timeoutSeconds: 2
      # volumes:
      #   - name: config-volume
      #     configMap:
      #       name: app-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-ruby-api
  namespace: myapps-ns
spec:
  selector:
    app: myapp-ruby-api
  type: NodePort
  ports:
    - port: 80 # forwarded port
      targetPort: 8081
      protocol: TCP
      nodePort: 30001 #Within default 30000-32767 minikube range. Port 30000 is taken for minikube's dashboard.
