apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-ruby-api
  namespace: myapps-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-ruby-api
  template:
    metadata:
      labels:
        app: myapp-ruby-api
    spec:
      containers:
        - name: myapp-ruby-api
          image: docker.io/kponnima86/myapp-ruby-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "100Mi"
              cpu: "300m"
            limits:
              memory: "200Mi"
              cpu: "600m"
          env:
            - name: PORT
              value: "8081"
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-ruby-api
  namespace: myapps-ns
spec:
  selector:
    app: myapp-ruby-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      nodePort: 31002 #Within default 30000-32767 minikube range
