AllCops:
  TargetRubyVersion: 3.1
Metrics/LineLength:
  Max: 120
Metrics/MethodLength: 
  Max: 20
Metrics/ClassLength:
  Max: 1500
Layout/EndOfLine:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Style/SymbolArray:
  Enabled: true
